baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Kagenti'
description = 'Kubernetes Agent Platform for AI with secure identity'
contentDir = 'content'
enableEmoji = true
tags = ['Kubernetes', 'agent', 'workload', 'platform', 'AI', 'LLM']

[module]
    # uncomment line below for temporary local development of module
    # or when using a 'theme' as a git submodule
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
    [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true

[params]
  [params.social]
    github = "https://github.com/orgs/kagenti/repositories"
    discord = "https://discord.gg/aJ92dNDzqB"
    youtube = "https://youtube.com/@Kagenti"
    email = "mailto:kagenti-maintainers@googlegroups.com"

[menu]
  [[menu.primary]]
    name  = "Blogs"
    url = "https://medium.com/kagenti-the-agentic-platform"
    identifier = "blogs"
    weight = 10